In [1]:
%pip install --break-system-packages pandas
import pandas as pd

df = pd.read_csv("../data/raw/flipkart_com-ecommerce_sample.csv")

print("Shape:", df.shape)

Requirement already satisfied: pandas in c:\users\sande\appdata\roaming\uv\python\cpython-3.14.0-windows-x86_64-none\lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in c:\users\sande\appdata\roaming\uv\python\cpython-3.14.0-windows-x86_64-none\lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sande\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\sande\appdata\roaming\uv\python\cpython-3.14.0-windows-x86_64-none\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\sande\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Shape: (20000, 15)

In [2]:
df.head()

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price,discounted_price,image,is_FK_Advantage_product,description,product_rating,overall_rating,brand,product_specifications
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,"[""http://img5a.flixcart.com/image/short/u/4/a/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",False,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,No rating available,No rating available,FabHomeDecor,"{""product_specification""=>[{""key""=>""Installati..."
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",False,Key Features of AW Bellies Sandals Wedges Heel...,No rating available,No rating available,AW,"{""product_specification""=>[{""key""=>""Ideal For""..."
3,0973b37acd0c664e3de26e97e5571454,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,"[""http://img5a.flixcart.com/image/short/6/2/h/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-all-purpose-arn...,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,"[""http://img5a.flixcart.com/image/pet-shampoo/...",False,Specifications of Sicons All Purpose Arnica Do...,No rating available,No rating available,Sicons,"{""product_specification""=>[{""key""=>""Pet Type"",..."

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   uniq_id                  20000 non-null  str
 1   crawl_timestamp          20000 non-null  str
 2   product_url              20000 non-null  str
 3   product_name             20000 non-null  str
 4   product_category_tree    20000 non-null  str
 5   pid                      20000 non-null  str
 6   retail_price             19922 non-null  float64
 7   discounted_price         19922 non-null  float64
 8   image                    19997 non-null  str
 9   is_FK_Advantage_product  20000 non-null  bool
 10  description              19998 non-null  str
 11  product_rating           20000 non-null  str
 12  overall_rating           20000 non-null  str
 13  brand                    14136 non-null  str
 14  product_specifications   19986 non-null  str
dtypes: bool(1), float64(2), str(12)
memory usage: 2.2 MB

In [4]:
pd.set_option("display.max_columns", None)

df.head(5)

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price,discounted_price,image,is_FK_Advantage_product,description,product_rating,overall_rating,brand,product_specifications
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,"[""http://img5a.flixcart.com/image/short/u/4/a/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",False,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,No rating available,No rating available,FabHomeDecor,"{""product_specification""=>[{""key""=>""Installati..."
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",False,Key Features of AW Bellies Sandals Wedges Heel...,No rating available,No rating available,AW,"{""product_specification""=>[{""key""=>""Ideal For""..."
3,0973b37acd0c664e3de26e97e5571454,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,"[""http://img5a.flixcart.com/image/short/6/2/h/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-all-purpose-arn...,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,"[""http://img5a.flixcart.com/image/pet-shampoo/...",False,Specifications of Sicons All Purpose Arnica Do...,No rating available,No rating available,Sicons,"{""product_specification""=>[{""key""=>""Pet Type"",..."

In [5]:
df[[
    "product_name",
    "product_category_tree",
    "retail_price",
    "discounted_price",
    "image",
    "description",
    "brand",
    "product_specifications"
]].head(5)

,product_name,product_category_tree,retail_price,discounted_price,image,description,brand,product_specifications
0,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",999.0,379.0,"[""http://img5a.flixcart.com/image/short/u/4/a/...",Key Features of Alisha Solid Women's Cycling S...,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
1,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",32157.0,22646.0,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",FabHomeDecor Fabric Double Sofa Bed (Finish Co...,FabHomeDecor,"{""product_specification""=>[{""key""=>""Installati..."
2,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",999.0,499.0,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",Key Features of AW Bellies Sandals Wedges Heel...,AW,"{""product_specification""=>[{""key""=>""Ideal For""..."
3,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",699.0,267.0,"[""http://img5a.flixcart.com/image/short/6/2/h/...",Key Features of Alisha Solid Women's Cycling S...,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
4,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",220.0,210.0,"[""http://img5a.flixcart.com/image/pet-shampoo/...",Specifications of Sicons All Purpose Arnica Do...,Sicons,"{""product_specification""=>[{""key""=>""Pet Type"",..."

In [6]:
df["product_category_tree"].value_counts().head(20)

product_category_tree
["Jewellery >> Necklaces & Chains >> Necklaces"]                                                       1567
["Jewellery >> Rings"]                                                                                  710
["Automotive >> Accessories & Spare parts >> Car Interior & Exterior >> Car Interior >> Car Mats"]      522
["Jewellery >> Bangles, Bracelets & Armlets >> Bangles"]                                                430
["Tools & Hardware >> Tools >> Gardening Tools >> Plant Containers & Sets >> Plant Container Sets"]     332
["Jewellery >> Bangles, Bracelets & Armlets >> Bracelets"]                                              251
["Mobiles & Accessories >> Tablet Accessories >> Cases & Covers >> TheLostPuppy Cases & Covers"]        229
["Clothing >> Women's Clothing >> Lingerie, Sleep & Swimwear >> Bras >> S4S Bras"]                      197
["Home Furnishing >> Bed Linen >> Blankets, Quilts & Dohars"]                                           190
["Footwear >> Women's Footwear >> Wedges"]                                                              186
["Jewellery >> Jewellery Sets"]                                                                         161
["Mobiles & Accessories >> Tablet Accessories >> Cases & Covers >> DailyObjects Cases & Covers"]        144
["Clothing >> Men's Clothing >> T-Shirts >> Numero Uno T-Shirts"]                                       135
["Home Furnishing >> Curtains & Accessories >> Curtains"]                                               131
["Footwear >> Women's Footwear >> Casual Shoes >> Boots"]                                               118
["Clothing >> Women's Clothing >> Lingerie, Sleep & Swimwear >> Bras >> Grafion Bras"]                  101
["Mobiles & Accessories >> Tablet Accessories >> Cases & Covers >> Enthopia Cases & Covers"]            101
["Footwear >> Women's Footwear >> Heels"]                                                                97
["Kitchen & Dining >> Coffee Mugs >> Prithish Coffee Mugs"]                                              94
["Home Furnishing >> Bath Linen >> Towels"]                                                              93
Name: count, dtype: int64

In [7]:
df["main_category"] = (
    df["product_category_tree"]
    .str.extract(r'\["([^>]+)')
    [0]
    .str.strip()
)

df["main_category"].value_counts()

main_category
Clothing                                                 6198
Jewellery                                                3531
Footwear                                                 1227
Mobiles & Accessories                                    1099
Automotive                                               1012
                                                         ...
Speedwav 186926 Royal Enfield 350 Twin Spark LED..."]       1
Speedwav 186879 Bajaj Pulsar 200 NS DTS-i LED In..."]       1
Pazel Slim Fit Men's Jeans"]                                1
SMART TRADERS Girls Bellies"]                               1
Areon Luxurious Fragrance Long Lasting Car,Home,..."]       1
Name: count, Length: 266, dtype: int64

In [8]:
df[df["main_category"].str.len() > 50][
    ["product_category_tree", "main_category"]
].head(10)

,product_category_tree,main_category
5,"[""Eternal Gandhi Super Series Crystal Paper We...",Eternal Gandhi Super Series Crystal Paper Weig...
30,"[""Bengal Blooms Rose Artificial Plant with Po...",Bengal Blooms Rose Artificial Plant with Pot ...
47,"[""BuildTrack PIR Wireless Motion Sensor - One ...",BuildTrack PIR Wireless Motion Sensor - One Sw...
48,"[""Skayvon SUMMERSIBLE SINGLE PHASE PUMP CONTRO...",Skayvon SUMMERSIBLE SINGLE PHASE PUMP CONTROLL...
52,"[""Skayvon SUBMERSIBBLE THREE PHASE PUMP CONTRO...",Skayvon SUBMERSIBBLE THREE PHASE PUMP CONTROLL...
327,"[""Cellbazaar Blackberry 8520 WHITE LCD LCD (YI...",Cellbazaar Blackberry 8520 WHITE LCD LCD (YIT-...
333,"[""Knight Ace Kraasa Sports Running Shoes, Cycl...","Knight Ace Kraasa Sports Running Shoes, Cyclin..."
1204,"[""Prime Printed 8 Seater Table Cover (Multicol...",Prime Printed 8 Seater Table Cover (Multicolor...
1288,"[""Speedwav 240437 Sun Shade For Hyundai i10 (D...",Speedwav 240437 Sun Shade For Hyundai i10 (Das...
1637,"[""K&P Dr.Ambedkar Large 04 Showpiece - 19 cm...",K&P Dr.Ambedkar Large 04 Showpiece - 19 cm (...

In [9]:
df["main_category"].value_counts().tail(20)

main_category
Autoplus M AP18 Arm Sleeve (Black)"]                     1
Kraft Seeds Thyme Herbs Seed (200 per packet)"]          1
Kraft Seeds Dill Herb Seed (50 per packet)"]             1
Leading lady Women's Camisole"]                          1
Yo Baby Girl's Trousers"]                                1
THERISE MD0005 Wired Headset (Pink)"]                    1
Nut Khut Embroidered Kurta & Churidar"]                  1
Vinenzia Printed Winter Men's Gloves"]                   1
Planet Waves Woodstock Strap (Multicolor)"]              1
Speedwav 216456 Manual Rear View Mirror (Right, ..."]    1
Speedwav 216510 Manual Rear View Mirror (Right, ..."]    1
Speedwav 216552 Manual Rear View Mirror (Right, ..."]    1
Speedwav 186136 Manual Rear View Mirror (Right, ..."]    1
Small Toes Bellies"]                                     1
Clovia Lingerie Set"]                                    1
Speedwav 186926 Royal Enfield 350 Twin Spark LED..."]    1
Speedwav 186879 Bajaj Pulsar 200 NS DTS-i LED In..."]    1
Pazel Slim Fit Men's Jeans"]                             1
SMART TRADERS Girls Bellies"]                            1
Areon Luxurious Fragrance Long Lasting Car,Home,..."]    1
Name: count, dtype: int64

In [10]:
for i in [0, 5, 30, 47, 100, 500]:
    print(f"\n--- Row {i} ---")
    print(df.loc[i, "product_category_tree"])

--- Row 0 ---
["Clothing >> Women's Clothing >> Lingerie, Sleep & Swimwear >> Shorts >> Alisha Shorts >> Alisha Solid Women's Cycling Shorts"]

--- Row 5 ---
["Eternal Gandhi Super Series Crystal Paper Weight..."]

--- Row 30 ---
["Bengal Blooms Rose Artificial Plant  with Pot (3..."]

--- Row 47 ---
["BuildTrack PIR Wireless Motion Sensor - One Swit..."]

--- Row 100 ---
["Watches >> Wrist Watches >> Rorlig Wrist Watches"]

--- Row 500 ---
["Footwear >> Women's Footwear >> Casual Shoes"]

In [11]:
print(df["product_category_tree"].iloc[0])
print(type(df["product_category_tree"].iloc[0]))

["Clothing >> Women's Clothing >> Lingerie, Sleep & Swimwear >> Shorts >> Alisha Shorts >> Alisha Solid Women's Cycling Shorts"]
<class 'str'>

In [12]:
import re

def extract_main_category(value):
    if pd.isna(value):
        return "Unknown"

    value = str(value)

    # Remove [" and "]
    value = value.strip('["]')

    # If there is no category hierarchy, mark it unknown
    if ">>" not in value:
        return "Unknown"

    # Take the first part before >>
    return value.split(">>")[0].strip()


df["main_category"] = df["product_category_tree"].apply(extract_main_category)

In [13]:
df["main_category"].value_counts()

main_category
Clothing                             6198
Jewellery                            3531
Footwear                             1227
Mobiles & Accessories                1099
Automotive                           1012
Home Decor & Festive Needs            929
Beauty and Personal Care              710
Home Furnishing                       700
Kitchen & Dining                      647
Computers                             578
Watches                               530
Baby Care                             483
Tools & Hardware                      391
Toys & School Supplies                330
Unknown                               328
Pens & Stationery                     313
Bags, Wallets & Belts                 265
Furniture                             180
Sports & Fitness                      166
Cameras & Accessories                  82
Home Improvement                       81
Health & Personal Care Appliances      43
Gaming                                 35
Sunglasses                             35
Pet Supplies                           30
Home & Kitchen                         24
Home Entertainment                     19
eBooks                                 15
Eyewear                                10
Household Supplies                      4
Food & Nutrition                        2
Wearable Smart Devices                  2
Automation & Robotics                   1
Name: count, dtype: int64

In [14]:
df["main_category"].value_counts().tail()

main_category
Eyewear                   10
Household Supplies         4
Food & Nutrition           2
Wearable Smart Devices     2
Automation & Robotics      1
Name: count, dtype: int64

In [15]:
print("Unknown:", (df["main_category"] == "Unknown").sum())
print("Total:", len(df))

Unknown: 328
Total: 20000

In [16]:
print("Total products:", len(df))
print("Duplicate product IDs:", df["pid"].duplicated().sum())
print("Duplicate product names:", df["product_name"].duplicated().sum())

Total products: 20000
Duplicate product IDs: 2
Duplicate product names: 7324

In [17]:
df[[
    "product_name",
    "description",
    "retail_price",
    "discounted_price",
    "image",
    "brand",
    "product_specifications"
]].isnull().sum()

product_name                 0
description                  2
retail_price                78
discounted_price            78
image                        3
brand                     5864
product_specifications      14
dtype: int64

In [18]:
df[df["image"].isna()][["pid", "product_name", "image"]]

                   pid                 product_name image
8600  WATDZ2ZQKHQKZGGT  SF by Sonata 7957PP06 Watch   NaN
8908  WATDZ2ZQGUATCWJT        Sonata 7945SM01 Watch   NaN
8943  WATDZ2ZQ8JPDHCTJ        Sonata 7016YM07 Watch   NaN

In [19]:
df[df["description"].isna()][["pid", "product_name", "description"]]

,pid,product_name,description
553,TOPEYV38KYVJKM54,Ozel Studio Casual Sleeveless Printed Women's Top,NaN
17299,CPCE2ZME2P7BMJFB,Amore Abstract Cushions Cover,NaN

In [20]:
df[df["pid"].duplicated(keep=False)][
    ["pid", "product_name", "brand", "image"]
]

,pid,product_name,brand,image
3188,JEAEGE8Q8GXYFTGU,TIMBERLAKE Slim Fit Fit Women's Blue Jeans,TIMBERLAKE,"[""http://img5a.flixcart.com/image/jean/g/p/z/a..."
7722,ACCEJ6TESY7AFT5W,Hako 60W Magsafe Laptop Charger For APPLE MacB...,Hako,"[""http://img6a.flixcart.com/image/laptop-adapt..."
7769,ACCEJ6TESY7AFT5W,Hako 60W Magsafe1 Laptop Charger For APPLE Mac...,Hako,"[""http://img6a.flixcart.com/image/laptop-adapt..."
9419,JEAEGE8Q8GXYFTGU,TIMBERLAKE Slim Fit Fit Women's Blue Jeans,TIMBERLAKE,"[""http://img5a.flixcart.com/image/jean/g/p/z/a..."

In [21]:
df = df.drop_duplicates(subset="pid", keep="first")

In [22]:
print("Products after removing duplicates:", len(df))
print("Duplicate PIDs:", df["pid"].duplicated().sum())

Products after removing duplicates: 19998
Duplicate PIDs: 0

In [23]:
df = df.drop_duplicates(subset="pid", keep="first")

print("Products after removing duplicates:", len(df))
print("Duplicate PIDs:", df["pid"].duplicated().sum())

Products after removing duplicates: 19998
Duplicate PIDs: 0

In [24]:
df = df.dropna(subset=["image"])

print("Products after removing missing images:", len(df))
print("Missing images:", df["image"].isna().sum())

Products after removing missing images: 19995
Missing images: 0

In [25]:
df["description"] = df["description"].fillna("")
df["product_specifications"] = df["product_specifications"].fillna("")
df["brand"] = df["brand"].fillna("Unknown")

In [26]:
print(df[[
    "description",
    "product_specifications",
    "brand"
]].isnull().sum())

description               0
product_specifications    0
brand                     0
dtype: int64

In [27]:
print(df["image"].iloc[0])

["http://img5a.flixcart.com/image/short/u/4/a/altht-3p-21-alisha-38-original-imaeh2d5vm5zbtgg.jpeg", "http://img5a.flixcart.com/image/short/p/j/z/altght4p-26-alisha-38-original-imaeh2d5kbufss6n.jpeg", "http://img5a.flixcart.com/image/short/p/j/z/altght4p-26-alisha-38-original-imaeh2d5npdybzyt.jpeg", "http://img5a.flixcart.com/image/short/z/j/7/altght-7-alisha-38-original-imaeh2d5jsz2ghd6.jpeg"]

In [28]:
import ast

def get_first_image_url(value):
    try:
        images = ast.literal_eval(value)
        
        if isinstance(images, list) and len(images) > 0:
            return images[0]
        
        return None
    
    except:
        return None

df["image_url"] = df["image"].apply(get_first_image_url)

In [29]:
print(df["image_url"].iloc[0])

http://img5a.flixcart.com/image/short/u/4/a/altht-3p-21-alisha-38-original-imaeh2d5vm5zbtgg.jpeg

In [30]:
print("Total products:", len(df))
print("Valid image URLs:", df["image_url"].notna().sum())
print("Missing image URLs:", df["image_url"].isna().sum())

Total products: 19995
Valid image URLs: 19995
Missing image URLs: 0

In [31]:
import requests
from PIL import Image
from io import BytesIO

test_urls = df["image_url"].head(10)

for i, url in enumerate(test_urls):
    try:
        response = requests.get(url, timeout=10)

        print(
            i,
            response.status_code,
            response.headers.get("Content-Type"),
            len(response.content)
        )

    except Exception as e:
        print(i, "ERROR:", e)

ModuleNotFoundError: No module named 'requests'

In [ ]:
import sys
print(sys.executable)

c:\Users\sande\AppData\Roaming\uv\python\cpython-3.14.0-windows-x86_64-none\python.exe

In [ ]:

%pip install requests pillow

Note: you may need to restart the kernel to use updated packages.

error: externally-managed-environment

× This environment is externally managed
╰─> This Python installation is managed by uv and should not be modified.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

In [32]:
%pip install --break-system-packages requests pillow
import pandas as pd
import requests
from PIL import Image

print("Pandas:", pd.__version__)
print("Requests:", requests.__version__)
print("Pillow:", Image.__version__)

Collecting requests
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting pillow
  Using cached pillow-12.3.0-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
Collecting charset_normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.5.1-cp314-cp314-win_amd64.whl.metadata (46 kB)
Collecting idna<4,>=2.5 (from requests)
  Using cached idna-3.19-py3-none-any.whl.metadata (9.2 kB)
Collecting urllib3<3,>=1.26 (from requests)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests)
  Downloading certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Downloading charset_normalizer-3.5.1-cp314-cp314-win_amd64.whl (204 kB)
Using cached idna-3.19-py3-none-any.whl (68 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Using cached pillow-12.3.0-cp314-cp314-win_amd64.whl (7.2 MB)
Downloading certifi-2026.7.22-py3-none-any.whl (136 kB)
Installing collected packages: urllib3, pillow, idna, charset_normalizer, certifi, requests

   ---------------------------------------- 0/6 [urllib3]
   ---------------------------------------- 0/6 [urllib3]
   ------ --------------------------------- 1/6 [pillow]
   ------ --------------------------------- 1/6 [pillow]
   ------ --------------------------------- 1/6 [pillow]
   ------ --------------------------------- 1/6 [pillow]
   ------ --------------------------------- 1/6 [pillow]
   ------------- -------------------------- 2/6 [idna]
   -------------------- ------------------- 3/6 [charset_normalizer]
   -------------------------- ------------- 4/6 [certifi]
   --------------------------------- ------ 5/6 [requests]
   ---------------------------------------- 6/6 [requests]

Successfully installed certifi-2026.7.22 charset_normalizer-3.5.1 idna-3.19 pillow-12.3.0 requests-2.34.2 urllib3-2.7.0
Note: you may need to restart the kernel to use updated packages.
Pandas: 3.0.5
Requests: 2.34.2
Pillow: 12.3.0

  WARNING: The script idna.exe is installed in 'c:\Users\sande\AppData\Roaming\uv\python\cpython-3.14.0-windows-x86_64-none\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script normalizer.exe is installed in 'c:\Users\sande\AppData\Roaming\uv\python\cpython-3.14.0-windows-x86_64-none\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.